# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d4795f7a9ad6c1a746d8c69fd39b2754ebf2de12815ea2f903d6143d345676de00f84e05ac3f2f8a4cf2aebfde0c958a503275c2beaf8780baaa707df3e9911

test:
  secret_key_base: a6295b600dccc06249e516c98ea6055a30a05dc96fbba2c82c8a51496886884689ddf747ceaa8e049c603047db91602102ca16ea0e63a5d6cb2abab90f8cf54d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
